import React from "react";
import type { Metadata } from "next";
import "@styles/globals.css";
import "@styles/scss/main.scss";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "../context/AuthContext";
import EduBot from "@components/EduBot";

export const metadata: Metadata = {
  title: "Edumate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Auth Provider wrapping the app */}
        <AuthProvider>
          {children}
          <Toaster position="bottom-center" reverseOrder={false} />
          {/* AI Chatbot - Available on all pages */}
          <EduBot />
        </AuthProvider>
      </body>
    </html>
  );
}
