import React from "react";
import type { Metadata } from "next";
import "@styles/scss/main.scss";
import Topbar from "@widgets/Student/common/Topbar";
import Sidebar from "@widgets/Student/common/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-screen h-screen flex flex-row overflow-x-hidden">
      <Sidebar />
      <div className="flex flex-col w-[87vw] ml-[18vw]">
        <Topbar />
        <div className="bg-primary/5 h-full w-full pt-[11vh] overflow-auto">
          {children}
        </div>
      </div>
    </div>
  );
}
